#!/bin/bash
# sra_fastq_download 0.1.0
# Generated by dx-app-wizard.

#####################################################
# Download single SRA accession
#
#  Input files:
#    none
#  Options:
#    $accession: string, space-sep. SRA accessions
#    $validate: boolean, run prefetch & vdb-validate
#    $advanced: string, additional arguments
#  Outputs:
#    reads_fastq: fastq file(s)
#####################################################
main() {
    set -e -x -o pipefail

    #
    # Get inputs and options
    # ---------------------------------------------------------------
    #

    echo "Value of accessions: '$accession'"
    echo "Value of validate:'$validate'"
    echo "Value of advanced: '$advanced'"

    #
    # if validate is true, run prefetch and vdb validate first
    # ---------------------------------------------------------------
    #
    if "$validate"; then
        echo "Running prefetch, vdb-validate and fastq-dump"
        prefetch "$accession" && vdb-validate "$accession"
    fi


    #
    # Configure the options
    # ---------------------------------------------------------------
    #
    added_cmd="$advanced"
    if [ "$output_type" == "fasta" ]; then
        added_cmd+=" --fasta "
    fi

    if [ "$gzip" == "true" ]; then
        added_cmd+=" --gzip "
    fi

    if [ "$split_files" == "true" ]; then
        added_cmd+=" --split-files "
    fi

    if [ "$read_ids" == "true" ]; then
        added_cmd+=" --readids "
    fi

    if [ "$dumpbase" == "true" ]; then
        added_cmd+=" --dumpbase "
    fi

    if [ "$skip_technical" == "true" ]; then
        added_cmd+=" --skip-technical "
    fi

    #
    # Run fastq-dump
    # ---------------------------------------------------------------
    #

    fastq-dump -h
    fastq-dump $added_cmd $accession

    #
    # Upload fastq plus paired fastq if PE
    # ---------------------------------------------------------------
    #

    for fn in *.fast*; do
        if [[ $fn == *_2.fast* ]]; then
            dx-jobutil-add-output reads2_fastq $(dx upload --brief "$fn") --class=array:file
        else
            dx-jobutil-add-output reads_fastq $(dx upload --brief "$fn") --class=array:file
        fi
    done

    echo "DONE"
}
